version: '3.8'
services:
  app:
    build: . # Assumes your Dockerfile is in the current directory
    ports:
      - '5000:5000'
    environment:
      # This path should correspond to where you COPY the credentials file in your Dockerfile
      FIREBASE_CREDENTIALS: /app/serviceAccountKey.json 
      FLASK_DEBUG: 'true' # Or 'false' for production
      FLASK_APP: 'app.py' # Explicitly set for clarity, though often inferred
      # DEEPSEEK_API_KEY should be securely managed, e.g., injected by CI/CD or Vercel env vars
      # For local docker-compose, you can use a .env file (docker-compose automatically loads it)
      # or pass it directly if not sensitive for local dev.
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY} 
    volumes:
      # If you are developing locally and want to map your local firebase credentials
      # ensure the source path is correct and the target path matches FIREBASE_CREDENTIALS
      # Example:
      # - ./path/to/your/local/serviceAccountKey.json:/app/serviceAccountKey.json:ro
      # The :ro makes it read-only in the container, which is good practice for credentials.
      # Ensure your .gitignore includes your actual credentials file.
      - .:/app # Mounts the current directory to /app in the container for hot-reloading (dev only)

# Removed 'db' service (Postgres) and 'db_data' volume
